// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlxqgasvhfohmmyftskf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhseHFnYXN2aGZvaG1teWZ0c2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTQ1MjQsImV4cCI6MjA2MzY5MDUyNH0.m9h9_1zwvdbQ4RTuXfAz6Llsix5YZFsWFYOizbTer78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);